export const dom = {
  appHeader: document.querySelector("app-header"),
  dataHubModal: document.querySelector("data-hub-modal"),
  controlsPanel: document.querySelector(".controls-panel"),
  inputsForm: document.getElementById("inputsForm"),
  inputsPanelContent: document.getElementById("inputsPanelContent"),

  resetInputs: document.getElementById("resetInputs"),
  toggleControlsBtn: document.getElementById("toggleControlsBtn"),
  easterEgg: document.getElementById("easterEgg"),

  presetSalary: document.getElementById("presetSalary"),
  presetStyleBtns: document.querySelectorAll(".preset-style-btn"),
  applyPresetBtn: document.getElementById("applyPresetBtn"),

  checkLatestVersion: document.getElementById("checkLatestVersion"),
  advancedSettings: document.getElementById("advancedSettings"),
  advancedTabExpense: document.getElementById("advancedTabExpense"),
  advancedTabSavings: document.getElementById("advancedTabSavings"),
  advancedTabInvest: document.getElementById("advancedTabInvest"),
  expenseAdvancedBlock: document.getElementById("expenseAdvancedBlock"),
  savingsAdvancedBlock: document.getElementById("savingsAdvancedBlock"),
  investAdvancedBlock: document.getElementById("investAdvancedBlock"),
  ratesAdvancedBlock: document.getElementById("ratesAdvancedBlock"),
  expenseSortMode: document.getElementById("expenseSortMode"),
  savingsSortMode: document.getElementById("savingsSortMode"),
  investSortMode: document.getElementById("investSortMode"),
  expenseGroupOptions: document.getElementById("expenseGroupOptions"),
  savingsGroupOptions: document.getElementById("savingsGroupOptions"),
  investGroupOptions: document.getElementById("investGroupOptions"),
  jumpAdvancedFields: Array.from(document.querySelectorAll(".jump-advanced-field")),

  saveViewToLocal: document.getElementById("saveViewToLocal"),
  viewModeGuide: document.getElementById("viewModeGuide"),
  viewModeGuideDontShow: document.getElementById("viewModeGuideDontShow"),
  dismissViewModeGuide: document.getElementById("dismissViewModeGuide"),
  returnToNormalMode: document.getElementById("returnToNormalMode"),
  jumpToTop: document.getElementById("jumpToTop"),
  applyFeedback: document.getElementById("applyFeedback"),
  summaryPanel: document.querySelector(".summary-panel"),
  summaryCards: document.getElementById("summaryCards"),
  financialSettingsDetail: document.getElementById("financialSettingsDetail"),
  sankeySvg: document.getElementById("sankeySvg"),
  sankeyWrap: document.getElementById("sankeyWrap"),
  sankeyMeta: document.getElementById("sankeyMeta"),
  sankeyLegend: document.getElementById("sankeyLegend"),
  sankeyViewAmount: document.getElementById("sankeyViewAmount"),
  sankeyViewPercent: document.getElementById("sankeyViewPercent"),
  sankeySortMode: document.getElementById("sankeySortMode"),
  sankeyGroupingExpense: document.getElementById("sankeyGroupingExpense"),
  sankeyGroupingSavings: document.getElementById("sankeyGroupingSavings"),
  sankeyGroupingInvest: document.getElementById("sankeyGroupingInvest"),
  sankeyExport: document.getElementById("sankeyExport"),
  sankeyEmpty: document.getElementById("sankeyEmpty"),
  sankeyTooltip: document.getElementById("sankeyTooltip"),
  toggleProjectionBtn: document.getElementById("toggleProjectionBtn"),
  projectionPanelContent: document.getElementById("projectionPanelContent"),
  projectionTableBody: document.querySelector("#projectionTable tbody"),
  projectionMeta: document.getElementById("projectionMeta"),
  modeTR: document.getElementById("modeTR"),
  modePR: document.getElementById("modePR"),
  colShowFlow: document.getElementById("colShowFlow"),
  colShowBalance: document.getElementById("colShowBalance"),
  colShowDividend: document.getElementById("colShowDividend"),
  
  openSmartAddBtn: document.getElementById("openSmartAddBtn"),
  smartAddModal: document.getElementById("smartAddModal"),
  closeSmartAddBtn: document.getElementById("closeSmartAddBtn"),
  smartAddInput: document.getElementById("smartAddInput"),
  smartAddResult: document.getElementById("smartAddResult"),
  smartAddAmount: document.getElementById("smartAddAmount"),
  smartAddMerchant: document.getElementById("smartAddMerchant"),
  smartAddDate: document.getElementById("smartAddDate"),
  smartAddCategory: document.getElementById("smartAddCategory"),
  applySmartAddBtn: document.getElementById("applySmartAddBtn"),

  openPresetBtn: document.getElementById("openPresetBtn"),
  presetModal: document.getElementById("presetModal"),
  closePresetBtn: document.getElementById("closePresetBtn"),
  closePresetModalCancel: document.getElementById("closePresetModalCancel"),
  presetBackBtn: document.getElementById("presetBackBtn"),
  applyModalPresetBtn: document.getElementById("applyModalPresetBtn"),
  presetSetupStep: document.getElementById("presetSetupStep"),
  presetConfirmStep: document.getElementById("presetConfirmStep"),
  presetMonthlyIncome: document.getElementById("presetMonthlyIncome"),
  presetSegmentGroup: document.getElementById("presetSegmentGroup"),
  presetSegmentBtns: document.querySelectorAll(".preset-segment-btn"),
  presetPercentInputs: document.querySelectorAll("[data-preset-percent]"),
  presetPercentTotal: document.getElementById("presetPercentTotal"),
  presetCorrectionModeInputs: document.querySelectorAll("input[name='presetCorrectionMode']"),
  presetPreviewTotal: document.getElementById("presetPreviewTotal"),
  presetPreviewRows: document.getElementById("presetPreviewRows"),

  financialModal: document.getElementById("financialModal"),
  financialModalTitle: document.getElementById("financialModalTitle"),
  financialModalDescription: document.getElementById("financialModalDescription"),
  financialModalClose: document.getElementById("financialModalClose"),
  financialModalSummary: document.getElementById("financialModalSummary"),
  financialModalCreate: document.getElementById("financialModalCreate"),
  financialModalRows: document.getElementById("financialModalRows"),
  financialModalCancel: document.getElementById("financialModalCancel"),
  financialModalSave: document.getElementById("financialModalSave"),
  financialModalPendingBar: document.getElementById("financialModalPendingBar"),

  snapshotSelector: document.getElementById("snapshotSelector"),
  saveSnapshotBtn: document.getElementById("saveSnapshotBtn"),
  deleteSnapshotBtn: document.getElementById("deleteSnapshotBtn"),
  comparisonContent: document.getElementById("comparisonContent"),
  comparisonExpenseSummary: document.getElementById("comparisonExpenseSummary"),
  comparisonSvg: document.getElementById("comparisonSvg"),
  comparisonEmpty: document.getElementById("comparisonEmpty"),

  appTitle: document.querySelector("h1"),
 
  // 시각화 토글 및 슬라이더 관련
  showSankeyBasicBtn: document.getElementById("showSankeyBasicBtn"),
  showSankeyDetailBtn: document.getElementById("showSankeyDetailBtn"),
  visualizationViewport: document.getElementById("visualizationViewport"),
  visualizationSlider: document.getElementById("visualizationSlider"),
 
  // 도움말 및 툴팁
  globalTooltip: document.getElementById("globalTooltip"),
  sankeyMetaTooltipTrigger: document.getElementById("sankeyMetaTooltipTrigger"),
  get globalFinancialIncomeIndicator() {
    return document.getElementById("globalFinancialIncomeIndicator");
  },
};
