export const dom = {
  appHeader: document.querySelector("app-header"),
  dataHubModal: document.querySelector("data-hub-modal"),
  controlsPanel: document.querySelector(".controls-panel"),
  inputsForm: document.getElementById("inputsForm"),
  inputsPanelContent: document.getElementById("inputsPanelContent"),

  resetInputs: document.getElementById("resetInputs"),
  toggleControlsBtn: document.getElementById("toggleControlsBtn"),
  easterEgg: document.getElementById("easterEgg"),

  presetSalary: document.getElementById("presetSalary"),
  presetStyleBtns: document.querySelectorAll(".preset-style-btn"),
  applyPresetBtn: document.getElementById("applyPresetBtn"),

  incomeList: document.getElementById("incomeList"),
  editIncomeItems: document.getElementById("editIncomeItems"),
  incomeEditorActions: document.getElementById("incomeEditorActions"),
  addIncomeItem: document.getElementById("addIncomeItem"),
  applyIncomeItems: document.getElementById("applyIncomeItems"),
  cancelIncomeItems: document.getElementById("cancelIncomeItems"),
  incomeTotalHint: document.getElementById("incomeTotalHint"),

  surplusTransferBanner: document.getElementById("surplusTransferBanner"),
  surplusAmountText: document.getElementById("surplusAmountText"),
  surplusTransferAccountSelect: document.getElementById("surplusTransferAccountSelect"),
  surplusNormalWrapper: document.getElementById("surplusNormalWrapper"),
  surplusDeficitWrapper: document.getElementById("surplusDeficitWrapper"),
  deficitAmountText: document.getElementById("deficitAmountText"),

  accountList: document.getElementById("accountList"),
  editAccountItems: document.getElementById("editAccountItems"),
  accountEditorActions: document.getElementById("accountEditorActions"),
  addAccountItem: document.getElementById("addAccountItem"),
  applyAccountItems: document.getElementById("applyAccountItems"),
  cancelAccountItems: document.getElementById("cancelAccountItems"),

  expenseList: document.getElementById("expenseList"),
  expenseTotalHint: document.getElementById("expenseTotalHint"),
  editExpenseItems: document.getElementById("editExpenseItems"),
  expenseEditorActions: document.getElementById("expenseEditorActions"),
  addExpenseItem: document.getElementById("addExpenseItem"),
  applyExpenseItems: document.getElementById("applyExpenseItems"),
  cancelExpenseItems: document.getElementById("cancelExpenseItems"),
  savingsList: document.getElementById("savingsList"),
  savingsTotalHint: document.getElementById("savingsTotalHint"),
  editSavingsItems: document.getElementById("editSavingsItems"),
  savingsEditorActions: document.getElementById("savingsEditorActions"),
  addSavingsItem: document.getElementById("addSavingsItem"),
  applySavingsItems: document.getElementById("applySavingsItems"),
  cancelSavingsItems: document.getElementById("cancelSavingsItems"),
  investList: document.getElementById("investList"),
  investTotalHint: document.getElementById("investTotalHint"),
  editInvestItems: document.getElementById("editInvestItems"),
  investEditorActions: document.getElementById("investEditorActions"),
  addInvestItem: document.getElementById("addInvestItem"),
  applyInvestItems: document.getElementById("applyInvestItems"),
  cancelInvestItems: document.getElementById("cancelInvestItems"),
  mobileEditorFab: document.getElementById("mobileEditorFab"),
  mobileEditorFabLabel: document.getElementById("mobileEditorFabLabel"),
  mobileEditorAdd: document.getElementById("mobileEditorAdd"),
  mobileEditorApply: document.getElementById("mobileEditorApply"),
  mobileEditorCancel: document.getElementById("mobileEditorCancel"),
  checkLatestVersion: document.getElementById("checkLatestVersion"),
  advancedSettings: document.getElementById("advancedSettings"),
  advancedTabExpense: document.getElementById("advancedTabExpense"),
  advancedTabSavings: document.getElementById("advancedTabSavings"),
  advancedTabInvest: document.getElementById("advancedTabInvest"),
  expenseAdvancedBlock: document.getElementById("expenseAdvancedBlock"),
  savingsAdvancedBlock: document.getElementById("savingsAdvancedBlock"),
  investAdvancedBlock: document.getElementById("investAdvancedBlock"),
  ratesAdvancedBlock: document.getElementById("ratesAdvancedBlock"),
  expenseSortMode: document.getElementById("expenseSortMode"),
  savingsSortMode: document.getElementById("savingsSortMode"),
  investSortMode: document.getElementById("investSortMode"),
  expenseGroupOptions: document.getElementById("expenseGroupOptions"),
  savingsGroupOptions: document.getElementById("savingsGroupOptions"),
  investGroupOptions: document.getElementById("investGroupOptions"),
  jumpAdvancedFields: Array.from(document.querySelectorAll(".jump-advanced-field")),

  saveViewToLocal: document.getElementById("saveViewToLocal"),
  viewModeGuide: document.getElementById("viewModeGuide"),
  viewModeGuideDontShow: document.getElementById("viewModeGuideDontShow"),
  dismissViewModeGuide: document.getElementById("dismissViewModeGuide"),
  returnToNormalMode: document.getElementById("returnToNormalMode"),
  jumpToTop: document.getElementById("jumpToTop"),
  applyFeedback: document.getElementById("applyFeedback"),
  summaryPanel: document.querySelector(".summary-panel"),
  summaryCards: document.getElementById("summaryCards"),
  sankeySvg: document.getElementById("sankeySvg"),
  sankeyWrap: document.getElementById("sankeyWrap"),
  sankeyMeta: document.getElementById("sankeyMeta"),
  sankeyCorrectionRefresh: document.getElementById("sankeyCorrectionRefresh"),
  sankeyCorrectionStatus: document.getElementById("sankeyCorrectionStatus"),
  sankeyLegend: document.getElementById("sankeyLegend"),
  accountTransferBoard: document.getElementById("accountTransferBoard"),
  transferCardList: document.getElementById("transferCardList"),
  sankeyViewAmount: document.getElementById("sankeyViewAmount"),
  sankeyViewPercent: document.getElementById("sankeyViewPercent"),
  sankeySortMode: document.getElementById("sankeySortMode"),
  sankeyGroupingExpense: document.getElementById("sankeyGroupingExpense"),
  sankeyGroupingSavings: document.getElementById("sankeyGroupingSavings"),
  sankeyGroupingInvest: document.getElementById("sankeyGroupingInvest"),
  sankeyExport: document.getElementById("sankeyExport"),
  sankeyEmpty: document.getElementById("sankeyEmpty"),
  sankeyTooltip: document.getElementById("sankeyTooltip"),
  toggleProjectionBtn: document.getElementById("toggleProjectionBtn"),
  projectionPanelContent: document.getElementById("projectionPanelContent"),
  projectionTableBody: document.querySelector("#projectionTable tbody"),
  projectionMeta: document.getElementById("projectionMeta"),
  modeTR: document.getElementById("modeTR"),
  modePR: document.getElementById("modePR"),
  colShowFlow: document.getElementById("colShowFlow"),
  colShowBalance: document.getElementById("colShowBalance"),
  colShowDividend: document.getElementById("colShowDividend"),
  
  openSmartAddBtn: document.getElementById("openSmartAddBtn"),
  smartAddModal: document.getElementById("smartAddModal"),
  closeSmartAddBtn: document.getElementById("closeSmartAddBtn"),
  smartAddInput: document.getElementById("smartAddInput"),
  smartAddResult: document.getElementById("smartAddResult"),
  smartAddAmount: document.getElementById("smartAddAmount"),
  smartAddMerchant: document.getElementById("smartAddMerchant"),
  smartAddDate: document.getElementById("smartAddDate"),
  smartAddCategory: document.getElementById("smartAddCategory"),
  applySmartAddBtn: document.getElementById("applySmartAddBtn"),

  openPresetBtn: document.getElementById("openPresetBtn"),
  presetModal: document.getElementById("presetModal"),
  closePresetBtn: document.getElementById("closePresetBtn"),
  closePresetModalCancel: document.getElementById("closePresetModalCancel"),
  presetBackBtn: document.getElementById("presetBackBtn"),
  applyModalPresetBtn: document.getElementById("applyModalPresetBtn"),
  presetSetupStep: document.getElementById("presetSetupStep"),
  presetConfirmStep: document.getElementById("presetConfirmStep"),
  presetMonthlyIncome: document.getElementById("presetMonthlyIncome"),
  presetSegmentGroup: document.getElementById("presetSegmentGroup"),
  presetSegmentBtns: document.querySelectorAll(".preset-segment-btn"),
  presetPercentInputs: document.querySelectorAll("[data-preset-percent]"),
  presetPercentTotal: document.getElementById("presetPercentTotal"),
  presetCorrectionModeInputs: document.querySelectorAll("input[name='presetCorrectionMode']"),
  presetPreviewTotal: document.getElementById("presetPreviewTotal"),
  presetPreviewRows: document.getElementById("presetPreviewRows"),

  financialModal: document.getElementById("financialModal"),
  financialModalTitle: document.getElementById("financialModalTitle"),
  financialModalDescription: document.getElementById("financialModalDescription"),
  financialModalClose: document.getElementById("financialModalClose"),
  financialModalSummary: document.getElementById("financialModalSummary"),
  financialModalCreate: document.getElementById("financialModalCreate"),
  financialModalRows: document.getElementById("financialModalRows"),
  financialModalCancel: document.getElementById("financialModalCancel"),
  financialModalSave: document.getElementById("financialModalSave"),
  financialModalPendingBar: document.getElementById("financialModalPendingBar"),

  snapshotSelector: document.getElementById("snapshotSelector"),
  saveSnapshotBtn: document.getElementById("saveSnapshotBtn"),
  deleteSnapshotBtn: document.getElementById("deleteSnapshotBtn"),
  comparisonContent: document.getElementById("comparisonContent"),
  comparisonExpenseSummary: document.getElementById("comparisonExpenseSummary"),
  comparisonSvg: document.getElementById("comparisonSvg"),
  comparisonEmpty: document.getElementById("comparisonEmpty"),

  appTitle: document.querySelector("h1"),
 
  // 시각화 토글 및 슬라이더 관련
  showSankeyBasicBtn: document.getElementById("showSankeyBasicBtn"),
  showSankeyDetailBtn: document.getElementById("showSankeyDetailBtn"),
  showNetworkBtn: document.getElementById("showNetworkBtn"),
  visualizationViewport: document.getElementById("visualizationViewport"),
  visualizationSlider: document.getElementById("visualizationSlider"),
  networkMapWrap: document.getElementById("networkMapWrap"),
  networkMapInner: document.getElementById("networkMapInner"),
  accountFlowNetworkMap: document.getElementById("accountFlowNetworkMap"),
  networkMapEmpty: document.getElementById("networkMapEmpty"),
 
  // 수동 이체 에디터 관련
  transferEditorSection: document.getElementById("transferEditorSection"),
  transferRuleForm: document.getElementById("transferRuleForm"),
  transferSourceSelect: document.getElementById("transferSourceSelect"),
  transferTargetSelect: document.getElementById("transferTargetSelect"),
  transferAmount: document.getElementById("transferAmount"),
  transferLabel: document.getElementById("transferLabel"),
  addTransferRuleBtn: document.getElementById("addTransferRuleBtn"),
  sourceBalanceHint: document.getElementById("sourceBalanceHint"),
  transferRuleList: document.getElementById("transferRuleList"),
 
  // 도움말 및 툴팁
  globalTooltip: document.getElementById("globalTooltip"),
  sankeyMetaTooltipTrigger: document.getElementById("sankeyMetaTooltipTrigger"),
  get globalFinancialIncomeIndicator() {
    return document.getElementById("globalFinancialIncomeIndicator");
  },
  pendingBar: document.getElementById("pendingBar"),
  pendingCancelBtn: document.getElementById("pendingCancelBtn"),
  pendingSaveBtn: document.getElementById("pendingSaveBtn"),
};
