/**
 * Step 2 DOM Elements
 */
export const dom = {
  appHeader: null,
  dataHubModal: null,
  bridgeBanner: null,
  dismissBridgeBanner: null,
  loadStep1Data: null,
  bridgeTimestamp: null,
  bridgeMonthlyInvestCapacity: null,
  chartMeta: null,
  chartTabSummary: null,
  chartTabAccount: null,
  chartTabFlow: null,
  summaryChartPane: null,
  accountChartPane: null,
  flowChartPane: null,
  summaryDonut: null,
  flowSankey: null,
  accountChartCards: null,
  amountBreakdown: null,
  portfolioName: null,
  portfolioNotes: null,
  totalMonthlyInvestCapacity: null,
  addAccount: null,
  accountList: null,
  accountSummary: null,
  savePortfolio: null,
  resetPortfolio: null,
  pendingBar: null,
  pendingSummary: null,
  applyChanges: null,
  cancelChanges: null,
  applyFeedback: null,
  toggleSimInputs: null,
  simInputsContainer: null,
  simDividendYield: null,
  simDividendGrowth: null,
  simCapitalGrowth: null,
  simHorizonYears: null,
  simDrip: null,
  simChartSvg: null,
  simChartTooltip: null,
  simTable: null,
  simYearsTabs: null,
};

export function initDom() {
  const selectors = {
    appHeader: "app-header",
    dataHubModal: "data-hub-modal",
    bridgeBanner: "bridgeBanner",
    dismissBridgeBanner: "dismissBridgeBanner",
    loadStep1Data: "loadStep1Data",
    bridgeTimestamp: "bridgeTimestamp",
    bridgeMonthlyInvestCapacity: "bridgeMonthlyInvestCapacity",
    chartMeta: "chartMeta",
    chartTabSummary: "chartTabSummary",
    chartTabAccount: "chartTabAccount",
    chartTabFlow: "chartTabFlow",
    summaryChartPane: "summaryChartPane",
    accountChartPane: "accountChartPane",
    flowChartPane: "flowChartPane",
    summaryDonut: "summaryDonut",
    flowSankey: "flowSankey",
    accountChartCards: "accountChartCards",
    amountBreakdown: "amountBreakdown",
    portfolioName: "portfolioName",
    portfolioNotes: "portfolioNotes",
    totalMonthlyInvestCapacity: "totalMonthlyInvestCapacity",
    addAccount: "addAccount",
    accountList: "accountList",
    accountSummary: "accountSummary",
    savePortfolio: "savePortfolio",
    resetPortfolio: "resetPortfolio",
    pendingBar: "pendingBar",
    pendingSummary: "pendingSummary",
    applyChanges: "applyChanges",
    cancelChanges: "cancelChanges",
    applyFeedback: "applyFeedback",
    toggleSimInputs: "toggleSimInputs",
    simInputsContainer: "simInputsContainer",
    simDividendYield: "simDividendYield",
    simDividendGrowth: "simDividendGrowth",
    simCapitalGrowth: "simCapitalGrowth",
    simHorizonYears: "simHorizonYears",
    simDrip: "simDrip",
    simChartSvg: "simChartSvg",
    simChartTooltip: "simChartTooltip",
    simYearsTabs: "simYearsTabs",
  };

  for (const [key, id] of Object.entries(selectors)) {
    dom[key] = document.getElementById(id) || document.querySelector(id);
  }
  dom.simTable = document.querySelector("#simTable tbody");
}
