
export const dom = {
  appHeader: null,
  dataHubModal: null,
  step1SyncBanner: null,
  dismissSyncBanner: null,
  importStep1Data: null,
  importStep1DataPrimary: null,
  resetStep2Simulation: null,
  syncTimestamp: null,
  syncInvestCapacity: null,
  totalInitialAsset: null,
  totalMonthlyInvestCapacity: null,
  applyFeedback: null,
  toggleSimInputs: null,
  simInputsContainer: null,
  saveStep2Simulation: null,
  strategyCardGroup: null,
  benchmarkSelect: null,
  coveredCallSelect: null,
  assumptionRangeNote: null,
  simDividendYield: null,
  simDividendGrowth: null,
  simCapitalGrowth: null,
  simHorizonYears: null,
  simDrip: null,
  simChartSvg: null,
  simChartTooltip: null,
  simTable: null,
  simYearsTabs: null,
  simKpiGrid: null,
  strategyComparisonCards: null,
  finalGuidance: null,
  detailSection: null,
  detailSummaryCards: null,
  activePresetName: null,
  optShowAsset: null,
  optShowDividend: null,
  optShowPR: null,
  optShowTR: null,
  dividendWarningBanner: null,
};

export function initDom() {
  const selectors = {
    appHeader: "app-header",
    dataHubModal: "data-hub-modal",
    step1SyncBanner: "step1SyncBanner",
    dismissSyncBanner: "dismissSyncBanner",
    importStep1Data: "importStep1Data",
    importStep1DataPrimary: "importStep1DataPrimary",
    resetStep2Simulation: "resetStep2Simulation",
    syncTimestamp: "syncTimestamp",
    syncInvestCapacity: "syncInvestCapacity",
    totalInitialAsset: "totalInitialAsset",
    totalMonthlyInvestCapacity: "totalMonthlyInvestCapacity",
    applyFeedback: "applyFeedback",
    toggleSimInputs: "toggleSimInputs",
    simInputsContainer: "simInputsContainer",
    saveStep2Simulation: "saveStep2Simulation",
    strategyCardGroup: "strategyCardGroup",
    benchmarkSelect: "benchmarkSelect",
    coveredCallSelect: "coveredCallSelect",
    assumptionRangeNote: "assumptionRangeNote",
    simDividendYield: "simDividendYield",
    simDividendGrowth: "simDividendGrowth",
    simCapitalGrowth: "simCapitalGrowth",
    simHorizonYears: "simHorizonYears",
    simDrip: "simDrip",
    simChartSvg: "simChartSvg",
    simChartTooltip: "simChartTooltip",
    simYearsTabs: "simYearsTabs",
    simKpiGrid: "simKpiGrid",
    strategyComparisonCards: "strategyComparisonCards",
    finalGuidance: "finalGuidance",
    detailSection: "detailSection",
    detailSummaryCards: "detailSummaryCards",
    activePresetName: "activePresetName",
    optShowAsset: "optShowAsset",
    optShowDividend: "optShowDividend",
    optShowPR: "optShowPR",
    optShowTR: "optShowTR",
    dividendWarningBanner: "dividendWarningBanner",
  };

  for (const [key, id] of Object.entries(selectors)) {
    dom[key] = document.getElementById(id) || document.querySelector(id);
  }
  dom.simTable = document.querySelector("#simTable tbody");
}


